include"splp/la05ds.inc"
include"splp/la05dd.inc"

MODULE optimization
  USE service, ONLY : SP, DP
  IMPLICIT NONE

CONTAINS
  include"splp/dfulmt.inc"
  include"splp/dpchng.inc"
  include"splp/dpincw.inc"
  include"splp/dpinit.inc"
  include"splp/dpintm.inc"
  include"splp/dplpce.inc"
  include"splp/dplpdm.inc"
  include"splp/dplpfe.inc"
  include"splp/dplpfl.inc"
  include"splp/dplpmn.inc"
  include"splp/dplpmu.inc"
  include"splp/dplpup.inc"
  include"splp/dpnnzr.inc"
  include"splp/dpopt.inc"
  include"splp/dsplp.inc"
  include"splp/dusrmt.inc"
  include"splp/fulmat.inc"
  include"splp/idloc.inc"
  include"splp/iploc.inc"
  include"splp/la05ad.inc"
  include"splp/la05as.inc"
  include"splp/la05bd.inc"
  include"splp/la05bs.inc"
  include"splp/la05cd.inc"
  include"splp/la05cs.inc"
  include"splp/la05ed.inc"
  include"splp/la05es.inc"
  include"splp/mc20ad.inc"
  include"splp/mc20as.inc"
  include"splp/pchngs.inc"
  include"splp/pinitm.inc"
  include"splp/pnnzrs.inc"
  include"splp/spincw.inc"
  include"splp/spinit.inc"
  include"splp/splp.inc"
  include"splp/splpce.inc"
  include"splp/splpdm.inc"
  include"splp/splpfe.inc"
  include"splp/splpfl.inc"
  include"splp/splpmn.inc"
  include"splp/splpmu.inc"
  include"splp/splpup.inc"
  include"splp/spopt.inc"
  include"splp/usrmat.inc"
END MODULE optimization