MODULE approximation
  USE service, ONLY : SP, DP
  USE blas
  USE linear  ! Required for defcmn.inc -> DBNDSL, DBNDAC
  USE data_handling  ! Required for defcmn.inc -> DSORT
  IMPLICIT NONE

CONTAINS
  include"minpack/chkder.inc"
  include"minpack/d1mpyq.inc"
  include"minpack/d1updt.inc"
  include"minpack/dckder.inc"
  include"minpack/dcov.inc"
  include"minpack/ddoglg.inc"
  include"minpack/dfdjc1.inc"
  include"minpack/dfdjc3.inc"
  include"minpack/dmpar.inc"
  include"minpack/dnls1.inc"
  include"minpack/dnls1e.inc"
  include"minpack/dnsq.inc"
  include"minpack/dnsqe.inc"
  include"minpack/dogleg.inc"
  include"minpack/dqform.inc"
  include"minpack/dqrfac.inc"
  include"minpack/dqrslv.inc"
  include"minpack/dwupdt.inc"
  include"minpack/fdjac1.inc"
  include"minpack/fdjac3.inc"
  include"minpack/lmpar.inc"
  include"minpack/qform.inc"
  include"minpack/qrfac.inc"
  include"minpack/qrsolv.inc"
  include"minpack/r1mpyq.inc"
  include"minpack/r1updt.inc"
  include"minpack/rwupdt.inc"
  include"minpack/scov.inc"
  include"minpack/snls1.inc"
  include"minpack/snls1e.inc"
  include"minpack/snsq.inc"
  include"minpack/snsqe.inc"
  include"bsplvd.inc"
  include"bsplvn.inc"
  include"cv.inc"
  include"dbocls.inc"
  include"dbols.inc"
  include"dbolsm.inc"
  include"dcv.inc"
  include"defc.inc"
  include"defcmn.inc"
  include"dfc.inc"
  include"dfcmn.inc"
  include"dfspvd.inc"
  include"dfspvn.inc"
  include"dlpdp.inc"
  include"dlsei.inc"
  include"dlsi.inc"
  include"dmout.inc"
  include"dp1vlu.inc"
  include"dpcoef.inc"
  include"dpolft.inc"
  include"dwnlit.inc"
  include"dwnlsm.inc"
  include"dwnlt1.inc"
  include"dwnlt2.inc"
  include"dwnlt3.inc"
  include"dwnnls.inc"
  include"efc.inc"
  include"efcmn.inc"
  include"fc.inc"
  include"fcmn.inc"
  include"lpdp.inc"
  include"lsei.inc"
  include"lsi.inc"
  include"pcoef.inc"
  include"polfit.inc"
  include"pvalue.inc"
  include"sbocls.inc"
  include"sbols.inc"
  include"sbolsm.inc"
  include"smout.inc"
  include"wnlit.inc"
  include"wnlsm.inc"
  include"wnlt1.inc"
  include"wnlt2.inc"
  include"wnlt3.inc"
  include"wnnls.inc"
END MODULE approximation