MODULE integ_trans
  USE service, ONLY : SP
  IMPLICIT NONE

CONTAINS
  include"fftpack/cfftb.inc"
  include"fftpack/cfftb1.inc"
  include"fftpack/cfftf.inc"
  include"fftpack/cfftf1.inc"
  include"fftpack/cffti.inc"
  include"fftpack/cffti1.inc"
  include"fftpack/cosqb.inc"
  include"fftpack/cosqb1.inc"
  include"fftpack/cosqf.inc"
  include"fftpack/cosqf1.inc"
  include"fftpack/cosqi.inc"
  include"fftpack/cost.inc"
  include"fftpack/costi.inc"
  include"fftpack/ezfft1.inc"
  include"fftpack/ezfftb.inc"
  include"fftpack/ezfftf.inc"
  include"fftpack/ezffti.inc"
  include"fftpack/passb.inc"
  include"fftpack/passb2.inc"
  include"fftpack/passb3.inc"
  include"fftpack/passb4.inc"
  include"fftpack/passb5.inc"
  include"fftpack/passf.inc"
  include"fftpack/passf2.inc"
  include"fftpack/passf3.inc"
  include"fftpack/passf4.inc"
  include"fftpack/passf5.inc"
  include"fftpack/radb2.inc"
  include"fftpack/radb3.inc"
  include"fftpack/radb4.inc"
  include"fftpack/radb5.inc"
  include"fftpack/radbg.inc"
  include"fftpack/radf2.inc"
  include"fftpack/radf3.inc"
  include"fftpack/radf4.inc"
  include"fftpack/radf5.inc"
  include"fftpack/radfg.inc"
  include"fftpack/rfftb.inc"
  include"fftpack/rfftb1.inc"
  include"fftpack/rfftf.inc"
  include"fftpack/rfftf1.inc"
  include"fftpack/rffti.inc"
  include"fftpack/rffti1.inc"
  include"fftpack/sinqb.inc"
  include"fftpack/sinqf.inc"
  include"fftpack/sinqi.inc"
  include"fftpack/sint.inc"
  include"fftpack/sinti.inc"
END MODULE integ_trans